### ISSUE TITLE
部分rtsp流无法播放

### ISSUE THREAD

**Issue by panliang-rm** [lckjcnWq/ijkplayer#3]
请问我拉摄像头的流地址，类似rtsp://admin:xxxxx@123@192.168.1.26:554/live/chn0这种可以播 ，但是类似rtsp://192.168.1.42:554/live/chn0播不出来

**Comment by lckjcnWq** [comment]
有没有可能是网络没有联通？需要贴出日志

**Comment by panliang-rm** [comment]
已定位到是播放流的参数，组播，单播
